In [1]:
if True:
    print("Leo")

Leo


In [2]:
if False:
    print("Leo")
print("Hello")

Hello


In [3]:
if True:
    print("Leo")
print("Hello")

Leo
Hello


In [5]:
x = 14
r = x % 2
if r == 0:
    print("x is even")
if r == 1:
    print("x is odd")

x is even


In [6]:
x = 14
r = x % 2
if r == 0:
    print("x is even")
else:
    print("x is odd")

x is even


In [7]:
x = 19
r = x % 2
if r == 0:
    print("x is even")
    if x > 10:
        print("x is greater than 10")
    else:
        print("x is less than 10")
else:
    print("x is odd")

x is odd


In [8]:
x = 12
r = x % 2
if r == 0:
    print("x is even")
    if x > 10:
        print("x is greater than 10")
    else:
        print("x is less than 10")
else:
    print("x is odd")

x is even
x is greater than 10


In [9]:
x = 4

if(x == 1):
    print("x is 1")
if(x == 2):
    print("x is 2")
if(x == 3):
    print("x is 3")
if(x == 4):
    print("x is 4")
if(x == 5):
    print("x is 5")

# This is a bad practice.

x is 4


In [10]:
x = 4

if(x == 1):
    print("x is 1")
elif(x == 2):
    print("x is 2")
elif(x == 3):
    print("x is 3")
elif(x == 4):
    print("x is 4")
elif(x == 5):
    print("x is 5")
else:
    print('x is not in this given list')

x is 4


In [11]:
x = 8

if(x == 1):
    print("x is 1")
elif(x == 2):
    print("x is 2")
elif(x == 3):
    print("x is 3")
elif(x == 4):
    print("x is 4")
elif(x == 5):
    print("x is 5")
else:
    print('x is not in this given list')

x is not in this given list


In [12]:
i = 1

while i < 6:
    print('Nucleya')
    i += 1

Nucleya
Nucleya
Nucleya
Nucleya
Nucleya


In [13]:
i = 10

while i > 6:
    print('Hello')
    i -= 1

Hello
Hello
Hello
Hello


In [14]:
i = 1

while i < 6:
    print('Entry',':',i-1)
    i += 1

Entry : 0
Entry : 1
Entry : 2
Entry : 3
Entry : 4


In [16]:
i = 1

while i < 6:
    print('Entry',':',i)
    j = 1
    while j < 4:
        print('Nested',':',j)
        j += 1
    i += 1
    print('End',':',i)
    print()
print('End of Loop')

Entry : 1
Nested : 1
Nested : 2
Nested : 3
End : 2

Entry : 2
Nested : 1
Nested : 2
Nested : 3
End : 3

Entry : 3
Nested : 1
Nested : 2
Nested : 3
End : 4

Entry : 4
Nested : 1
Nested : 2
Nested : 3
End : 5

Entry : 5
Nested : 1
Nested : 2
Nested : 3
End : 6

End of Loop


In [18]:
i = 1

while i < 6:
    print('Entry',':',i, end = ' ')
    j = 1
    while j < 4:
        print('Nested',':',j, end = '')
        j += 1
    i += 1
    print('End',':',i)
    print()

Entry : 1 Nested : 1Nested : 2Nested : 3End : 2

Entry : 2 Nested : 1Nested : 2Nested : 3End : 3

Entry : 3 Nested : 1Nested : 2Nested : 3End : 4

Entry : 4 Nested : 1Nested : 2Nested : 3End : 5

Entry : 5 Nested : 1Nested : 2Nested : 3End : 6



In [19]:
i  = 1

while i < 6:
    print('Entry',':',i, end = ' *')
    j = 1
    while j < 4:
        print('Nested',':',j, end = ' ')
        j += 1
    i += 1
    print('End',':',i)
    print()

Entry : 1 *Nested : 1 Nested : 2 Nested : 3 End : 2

Entry : 2 *Nested : 1 Nested : 2 Nested : 3 End : 3

Entry : 3 *Nested : 1 Nested : 2 Nested : 3 End : 4

Entry : 4 *Nested : 1 Nested : 2 Nested : 3 End : 5

Entry : 5 *Nested : 1 Nested : 2 Nested : 3 End : 6



In [20]:
i = 1

while i < 6:
    j = 0 
    while j < 4:
        print(i*j, end = ' ')
        j += 1
    print()
    i += 1

0 1 2 3 
0 2 4 6 
0 3 6 9 
0 4 8 12 
0 5 10 15 


In [21]:
i = 1

while i < 6:
    j = 0 
    while j < 20:
        print(i*j, end = ' ')
        j += 1
    print()
    i += 1

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 
0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 
0 3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 
0 4 8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 
0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 


In [23]:
name = 'Leo'
for i in name:
    print(i)

L
e
o


In [24]:
for i in [1,-2,7.954,'Hello',[1,2,3]]:
    print(i)

1
-2
7.954
Hello
[1, 2, 3]


In [25]:
for i in range(6):
    print(i)

0
1
2
3
4
5


In [26]:
for i in range (2,6):
    print(i)

2
3
4
5


In [27]:
for i in range(10,26,2):
    print(i)

10
12
14
16
18
20
22
24


In [28]:
for i in range(3,17):
    if i % 2 != 0:
        print(i)

3
5
7
9
11
13
15


In [29]:
for i in range(3,17):
    if i == 8:
        break
    print(i)

3
4
5
6
7


In [30]:
for i in range(10453,10493):
    if i % 17 == 0:
        break
print(i)

10455


In [33]:
for i in range(1,20):
    if i % 3 == 0:
        continue
    print(i)

1
2
4
5
7
8
10
11
13
14
16
17
19


In [34]:
for i in range(1,9):
    if i == 5:
        continue
    print(i)

1
2
3
4
6
7
8


In [35]:
for i in range(1,9):
    if i == 5:
        pass
    print(i)

1
2
3
4
5
6
7
8


In [36]:
print('# # # #')
print('# # # #')
print('# # # #')
print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [37]:
for i in range(5):
    print ("#", end = " ")

# # # # # 

In [38]:
for i in range(5):
    print ("#", end = "\n")

#
#
#
#
#


In [39]:
for i in range(5):
    print ("#", end = " ")
for j in range(5):
    print ("#", end = "\n")

# # # # # #
#
#
#
#


In [40]:
def print_diamond(size):
    # Print the upper part of the diamond
    for i in range(size):
        # Print leading spaces
        print(' ' * (size - i - 1), end='')
        # Print stars
        print('*' * (2 * i + 1))
    
    # Print the lower part of the diamond
    for i in range(size - 2, -1, -1):
        # Print leading spaces
        print(' ' * (size - i - 1), end='')
        # Print stars
        print('*' * (2 * i + 1))

# Call the function with desired size
print_diamond(10)


         *
        ***
       *****
      *******
     *********
    ***********
   *************
  ***************
 *****************
*******************
 *****************
  ***************
   *************
    ***********
     *********
      *******
       *****
        ***
         *


In [41]:
for i in range (5):
    for j in range (i):
        print ("*", end = " ")
    print()


* 
* * 
* * * 
* * * * 


In [42]:
nums = [ 12,14,18,27,15,12]
for num in nums:
    if num % 3 == 0:
        print(num)

12
18
27
15
12


In [43]:
nums = [ 12,14,18,27,15,12]
for num in nums:
    if num % 3 == 0:
        print(num)
        if num > 17:
            break

12
18


In [1]:
nums = [ 12,14,18,27,15,12]
for num in nums:
    if num % 5 == 0:
        print(num)
        if num > 17:
            break
    else:
        print('Number not found')

Number not found
Number not found
Number not found
Number not found
15
Number not found


In [3]:
nums = [ 12,14,18,27,15,12]
for num in nums:
    if num % 5 == 0:
        print(num)
else:
    print('Number not found')

15
Number not found


In [4]:
nums = [ 12,14,18,27,15,12]
for num in nums:
    if num % 5 == 0:
        print(num)
        break
else:
    print('Number not found')

15


In [5]:
num = 12
for i in range(2,num):
    if num % i == 0:
        print(num, 'is not a prime number')
        break
else:
    print(num, 'is a prime number')

12 is not a prime number


In [6]:
num = 17
for i in range(2,num):
    if num % i == 0:
        print(num, 'is not a prime number')
        break
else:
    print(num, 'is a prime number')

17 is a prime number


In [4]:
from array import *
arr = array('i',[])
n = int(input('Enter the length of array:'))

for i in range(7):
    x = int(input('Enter the next number:'))
    arr.append(x)
    print(arr)

array('i', [3])
array('i', [3, 4])
array('i', [3, 4, 5])
array('i', [3, 4, 5, 6])
array('i', [3, 4, 5, 6, 7])
array('i', [3, 4, 5, 6, 7, 8])
array('i', [3, 4, 5, 6, 7, 8, 9])


In [5]:
from numpy import *
arr = array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [6]:
print(arr.dtype)

int32


In [7]:
arr = array([1,2,3.7,4,5])
print(arr)
type(arr)
print(arr.dtype)

[1.  2.  3.7 4.  5. ]
float64


In [9]:
import numpy as np

arr = np.linspace(1,17,32,14,5)
print(arr)

(array([ 1.        ,  1.51612903,  2.03225806,  2.5483871 ,  3.06451613,
        3.58064516,  4.09677419,  4.61290323,  5.12903226,  5.64516129,
        6.16129032,  6.67741935,  7.19354839,  7.70967742,  8.22580645,
        8.74193548,  9.25806452,  9.77419355, 10.29032258, 10.80645161,
       11.32258065, 11.83870968, 12.35483871, 12.87096774, 13.38709677,
       13.90322581, 14.41935484, 14.93548387, 15.4516129 , 15.96774194,
       16.48387097, 17.        ]), 0.5161290322580645)


In [10]:
arr = np.arange(1,17,2)
print(arr)

[ 1  3  5  7  9 11 13 15]


In [11]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])